# Generated by Django 4.2.7 on 2023-11-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_hotel_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='Img',
        ),
    ]
